/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResidentialRouteImport } from './routes/residential'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResidentialTypeIdRouteImport } from './routes/residential.$type.$id'

const ResidentialRoute = ResidentialRouteImport.update({
  id: '/residential',
  path: '/residential',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResidentialTypeIdRoute = ResidentialTypeIdRouteImport.update({
  id: '/$type/$id',
  path: '/$type/$id',
  getParentRoute: () => ResidentialRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/residential': typeof ResidentialRouteWithChildren
  '/residential/$type/$id': typeof ResidentialTypeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/residential': typeof ResidentialRouteWithChildren
  '/residential/$type/$id': typeof ResidentialTypeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/residential': typeof ResidentialRouteWithChildren
  '/residential/$type/$id': typeof ResidentialTypeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/residential' | '/residential/$type/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/residential' | '/residential/$type/$id'
  id: '__root__' | '/' | '/residential' | '/residential/$type/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ResidentialRoute: typeof ResidentialRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/residential': {
      id: '/residential'
      path: '/residential'
      fullPath: '/residential'
      preLoaderRoute: typeof ResidentialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/residential/$type/$id': {
      id: '/residential/$type/$id'
      path: '/$type/$id'
      fullPath: '/residential/$type/$id'
      preLoaderRoute: typeof ResidentialTypeIdRouteImport
      parentRoute: typeof ResidentialRoute
    }
  }
}

interface ResidentialRouteChildren {
  ResidentialTypeIdRoute: typeof ResidentialTypeIdRoute
}

const ResidentialRouteChildren: ResidentialRouteChildren = {
  ResidentialTypeIdRoute: ResidentialTypeIdRoute,
}

const ResidentialRouteWithChildren = ResidentialRoute._addFileChildren(
  ResidentialRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ResidentialRoute: ResidentialRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
